language: scala

scala:
   - 2.10.7
   - 2.11.12
   - 2.12.6
   
script:
   - sbt ++$TRAVIS_SCALA_VERSION test

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8