language: java
env:
  - SCALA_VERSION=2.11.12
os:
  - osx
script:
  - ./sbt "++$SCALA_VERSION" test
matrix:
  include:
    - env: SCALA_VERSION=2.12.6
      os: linux
      jdk: oraclejdk8
    - env: SCALA_VERSION=2.11.12
      os: linux
      jdk: oraclejdk8
    - env: SCALA_VERSION=2.10.7
      os: linux
      jdk: oraclejdk8